### ISSUE TITLE
Mixed history

### ISSUE THREAD

**Issue by rgrinberg** [naddeoa/git-bulk#1]
Would be great if `$ git bulk log -a` had a mode to sort the commits according to chronological order rather than be grouped by the repository. This is useful to get a feel for the changes happening to a multi repo project.

**Comment by naddeoa** [comment]
That actually does sound pretty useful. I'm a little disappointing I didn't think of it first. I'll try to take a look this weekend.

**Comment by naddeoa** [comment]
Pushed out a rough draft to npm. If you reinstall with `npm install git-bulk` then you should be able to try it out with `git bulk log -ac`. Its added to the help menu also under `git bulk help log`.

Might have to clean up the output a little but I like the feature.

**Comment by rgrinberg** [comment]
Thanks!

**Comment by naddeoa** [comment]
I'm going to close this out. Feel free to open it up if there is something wrong.
